[package]
name = "day03"
version = "0.1.0"
authors = ["HeadBeeGuy <35615790+HeadBeeGuy@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
